/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package frontend;

/**
 *
 * @author Diego
 */
public class InternGuarniciones extends javax.swing.JInternalFrame {

    /**
     * Creates new form InternGuarniciones
     */
    public InternGuarniciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        img_ensaladaPapa = new javax.swing.JLabel();
        img_purePapa = new javax.swing.JLabel();
        img_papasFrancesa = new javax.swing.JLabel();
        precio1 = new javax.swing.JLabel();
        lbl_papasFrancesa = new javax.swing.JLabel();
        lbl_purePapa = new javax.swing.JLabel();
        txt_descripcion1 = new javax.swing.JTextArea();
        txt_descripcion2 = new javax.swing.JTextArea();
        txt_descripcion3 = new javax.swing.JTextArea();
        lbl_ensaladaPapa1 = new javax.swing.JLabel();
        precio2 = new javax.swing.JLabel();
        precio3 = new javax.swing.JLabel();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        img_ensaladaPapa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/MenuEnsaladaPapa.jpg"))); // NOI18N
        jPanel1.add(img_ensaladaPapa, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 6, 181, -1));

        img_purePapa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/MenuPurePapa.jpg"))); // NOI18N
        jPanel1.add(img_purePapa, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 180, -1));

        img_papasFrancesa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/MenuPapasFrancesa.jpg"))); // NOI18N
        jPanel1.add(img_papasFrancesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 138, 194, -1));

        precio1.setFont(new java.awt.Font("MV Boli", 1, 20)); // NOI18N
        precio1.setForeground(new java.awt.Color(253, 212, 51));
        precio1.setText("$35");
        jPanel1.add(precio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 50, -1, -1));

        lbl_papasFrancesa.setFont(new java.awt.Font("MV Boli", 1, 16)); // NOI18N
        lbl_papasFrancesa.setForeground(new java.awt.Color(253, 212, 51));
        lbl_papasFrancesa.setText("Papas a la Francesa");
        jPanel1.add(lbl_papasFrancesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 138, -1, -1));

        lbl_purePapa.setFont(new java.awt.Font("MV Boli", 1, 16)); // NOI18N
        lbl_purePapa.setForeground(new java.awt.Color(253, 212, 51));
        lbl_purePapa.setText("Puré de papa");
        jPanel1.add(lbl_purePapa, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 270, -1, -1));

        txt_descripcion1.setEditable(false);
        txt_descripcion1.setBackground(new java.awt.Color(0, 0, 0));
        txt_descripcion1.setColumns(20);
        txt_descripcion1.setFont(new java.awt.Font("Cascadia Mono", 0, 12)); // NOI18N
        txt_descripcion1.setForeground(new java.awt.Color(255, 255, 255));
        txt_descripcion1.setRows(5);
        txt_descripcion1.setText("300 Gramos de ensalada de papa fría \ncon apio, para acompañar con tu\npollo o platillo favorito.");
        txt_descripcion1.setBorder(null);
        jPanel1.add(txt_descripcion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 257, -1));

        txt_descripcion2.setEditable(false);
        txt_descripcion2.setBackground(new java.awt.Color(0, 0, 0));
        txt_descripcion2.setColumns(20);
        txt_descripcion2.setFont(new java.awt.Font("Cascadia Mono", 0, 12)); // NOI18N
        txt_descripcion2.setForeground(new java.awt.Color(255, 255, 255));
        txt_descripcion2.setRows(5);
        txt_descripcion2.setText("250 Gramos de papas a la francesa\ncon especias, acompañadas de tus\naderezos de preferencia.");
        txt_descripcion2.setBorder(null);
        jPanel1.add(txt_descripcion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 167, 257, -1));

        txt_descripcion3.setEditable(false);
        txt_descripcion3.setBackground(new java.awt.Color(0, 0, 0));
        txt_descripcion3.setColumns(20);
        txt_descripcion3.setFont(new java.awt.Font("Cascadia Mono", 0, 12)); // NOI18N
        txt_descripcion3.setForeground(new java.awt.Color(255, 255, 255));
        txt_descripcion3.setRows(5);
        txt_descripcion3.setText("350 Gramos de puré de papa\ncon gravy.");
        txt_descripcion3.setBorder(null);
        jPanel1.add(txt_descripcion3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 257, -1));

        lbl_ensaladaPapa1.setFont(new java.awt.Font("MV Boli", 1, 16)); // NOI18N
        lbl_ensaladaPapa1.setForeground(new java.awt.Color(253, 212, 51));
        lbl_ensaladaPapa1.setText("Ensalada de papa");
        jPanel1.add(lbl_ensaladaPapa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        precio2.setFont(new java.awt.Font("MV Boli", 1, 20)); // NOI18N
        precio2.setForeground(new java.awt.Color(253, 212, 51));
        precio2.setText("$40");
        jPanel1.add(precio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, -1, -1));

        precio3.setFont(new java.awt.Font("MV Boli", 1, 20)); // NOI18N
        precio3.setForeground(new java.awt.Color(253, 212, 51));
        precio3.setText("$30");
        jPanel1.add(precio3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 300, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel img_ensaladaPapa;
    private javax.swing.JLabel img_papasFrancesa;
    private javax.swing.JLabel img_purePapa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_ensaladaPapa1;
    private javax.swing.JLabel lbl_papasFrancesa;
    private javax.swing.JLabel lbl_purePapa;
    private javax.swing.JLabel precio1;
    private javax.swing.JLabel precio2;
    private javax.swing.JLabel precio3;
    private javax.swing.JTextArea txt_descripcion1;
    private javax.swing.JTextArea txt_descripcion2;
    private javax.swing.JTextArea txt_descripcion3;
    // End of variables declaration//GEN-END:variables
}
