/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package frontend;

/**
 *
 * @author Diego
 */
public class InternRefrescos extends javax.swing.JInternalFrame {

    /**
     * Creates new form InternGuarniciones
     */
    public InternRefrescos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        img_refrescos = new javax.swing.JLabel();
        precio1 = new javax.swing.JLabel();
        lbl_aguaMineral = new javax.swing.JLabel();
        lbl_refrescos = new javax.swing.JLabel();
        list_aguaMineral = new javax.swing.JList<>();
        list_refrescos = new javax.swing.JList<>();
        precio2 = new javax.swing.JLabel();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        img_refrescos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/MenuRefrescos.jpg"))); // NOI18N
        jPanel1.add(img_refrescos, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 300, 170));

        precio1.setFont(new java.awt.Font("MV Boli", 1, 20)); // NOI18N
        precio1.setForeground(new java.awt.Color(255, 204, 102));
        precio1.setText("$15");
        jPanel1.add(precio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, -1, -1));

        lbl_aguaMineral.setFont(new java.awt.Font("MV Boli", 1, 16)); // NOI18N
        lbl_aguaMineral.setForeground(new java.awt.Color(204, 255, 153));
        lbl_aguaMineral.setText("Agua Mineral");
        jPanel1.add(lbl_aguaMineral, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        lbl_refrescos.setFont(new java.awt.Font("MV Boli", 1, 16)); // NOI18N
        lbl_refrescos.setForeground(new java.awt.Color(255, 204, 102));
        lbl_refrescos.setText("Refrescos");
        jPanel1.add(lbl_refrescos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        list_aguaMineral.setBackground(new java.awt.Color(0, 0, 0));
        list_aguaMineral.setBorder(null);
        list_aguaMineral.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        list_aguaMineral.setForeground(new java.awt.Color(255, 255, 255));
        list_aguaMineral.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "-Peñafiel", "-Topochico", "-Skarch" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        list_aguaMineral.setFocusable(false);
        jPanel1.add(list_aguaMineral, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 120, -1));

        list_refrescos.setBackground(new java.awt.Color(0, 0, 0));
        list_refrescos.setBorder(null);
        list_refrescos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        list_refrescos.setForeground(new java.awt.Color(255, 255, 255));
        list_refrescos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "-Coca Cola", "-Sprite", "-Mirinda", "-Manzanita", "-Tonicol", "-Pepsi" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        list_refrescos.setFocusable(false);
        jPanel1.add(list_refrescos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 120, -1));

        precio2.setFont(new java.awt.Font("MV Boli", 1, 20)); // NOI18N
        precio2.setForeground(new java.awt.Color(153, 255, 153));
        precio2.setText("$15");
        jPanel1.add(precio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel img_refrescos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_aguaMineral;
    private javax.swing.JLabel lbl_refrescos;
    private javax.swing.JList<String> list_aguaMineral;
    private javax.swing.JList<String> list_refrescos;
    private javax.swing.JLabel precio1;
    private javax.swing.JLabel precio2;
    // End of variables declaration//GEN-END:variables
}
