/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package frontend;

/**
 *
 * @author Diego
 */
public class InternAguas extends javax.swing.JInternalFrame {

    /**
     * Creates new form InternGuarniciones
     */
    public InternAguas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        img_aguas = new javax.swing.JLabel();
        precio1 = new javax.swing.JLabel();
        lbl_aguaMineral = new javax.swing.JLabel();
        lbl_aguas = new javax.swing.JLabel();
        list_aguaMineral = new javax.swing.JList<>();
        list_refrescos = new javax.swing.JList<>();
        precio2 = new javax.swing.JLabel();
        img_aguas2 = new javax.swing.JLabel();
        precio3 = new javax.swing.JLabel();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        img_aguas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/MenuAguaSabor.jpg"))); // NOI18N
        jPanel1.add(img_aguas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 250, 150));

        precio1.setFont(new java.awt.Font("MV Boli", 1, 20)); // NOI18N
        precio1.setForeground(new java.awt.Color(255, 255, 255));
        precio1.setText("Chica $20");
        jPanel1.add(precio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, -1, -1));

        lbl_aguaMineral.setFont(new java.awt.Font("MV Boli", 1, 16)); // NOI18N
        lbl_aguaMineral.setForeground(new java.awt.Color(255, 153, 51));
        lbl_aguaMineral.setText("Agua natural");
        jPanel1.add(lbl_aguaMineral, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, -1, -1));

        lbl_aguas.setFont(new java.awt.Font("MV Boli", 1, 16)); // NOI18N
        lbl_aguas.setForeground(new java.awt.Color(255, 204, 51));
        lbl_aguas.setText("Agua de sabor");
        lbl_aguas.setToolTipText("");
        jPanel1.add(lbl_aguas, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, -1));

        list_aguaMineral.setBackground(new java.awt.Color(0, 0, 0));
        list_aguaMineral.setBorder(null);
        list_aguaMineral.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        list_aguaMineral.setForeground(new java.awt.Color(255, 255, 255));
        list_aguaMineral.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "-Epura", "-Ciel", "-Bonafont", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        list_aguaMineral.setFocusable(false);
        jPanel1.add(list_aguaMineral, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 120, 70));

        list_refrescos.setBackground(new java.awt.Color(0, 0, 0));
        list_refrescos.setBorder(null);
        list_refrescos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        list_refrescos.setForeground(new java.awt.Color(255, 255, 255));
        list_refrescos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "-Lima", "-Horchata", "-Jamaica", "-Limon", "-Piña", "-Naranja" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        list_refrescos.setFocusable(false);
        jPanel1.add(list_refrescos, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 120, -1));

        precio2.setFont(new java.awt.Font("MV Boli", 1, 20)); // NOI18N
        precio2.setForeground(new java.awt.Color(255, 255, 255));
        precio2.setText("$12");
        precio2.setToolTipText("");
        jPanel1.add(precio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, -1, -1));

        img_aguas2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/MenuAguaSabor2.jpg"))); // NOI18N
        jPanel1.add(img_aguas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 250, 140));

        precio3.setFont(new java.awt.Font("MV Boli", 1, 20)); // NOI18N
        precio3.setForeground(new java.awt.Color(255, 255, 255));
        precio3.setText("Grande $26");
        precio3.setToolTipText("");
        jPanel1.add(precio3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel img_aguas;
    private javax.swing.JLabel img_aguas2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_aguaMineral;
    private javax.swing.JLabel lbl_aguas;
    private javax.swing.JList<String> list_aguaMineral;
    private javax.swing.JList<String> list_refrescos;
    private javax.swing.JLabel precio1;
    private javax.swing.JLabel precio2;
    private javax.swing.JLabel precio3;
    // End of variables declaration//GEN-END:variables
}
