
package frontend;

import backend.Cliente;
import java.awt.Color;
import javax.swing.JOptionPane;
import basedatos.BD;
import javax.swing.table.DefaultTableModel;


public class VtnCliente extends javax.swing.JFrame {
    
    VtnPrincipal objVtnPrincipal = null;
    Cliente objCliente = null;
    BD objBd = null;
    DefaultTableModel modeloCliente = new DefaultTableModel();
    
    
    public VtnCliente() {
        
        initComponents();
    }
    public VtnCliente(VtnPrincipal objVtnPrincipal, Cliente objCliente) {
        initComponents();
        
        btngroup_masculinoFemenino.add(radbtn_masculino);
        btngroup_masculinoFemenino.add(radbtn_femenino);
        
        this.setLocationRelativeTo(null);
        this.objVtnPrincipal = objVtnPrincipal;
        objBd = new BD();
        this.objCliente = objCliente;
        modeloCliente = objBd.crear_modelo_cliente(modeloCliente);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngroup_masculinoFemenino = new javax.swing.ButtonGroup();
        pnl_fondo = new javax.swing.JPanel();
        img_logo = new javax.swing.JLabel();
        btn_regresar = new javax.swing.JLabel();
        lbl_titulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        pnl_cliente = new javax.swing.JTabbedPane();
        pnl_ingresar = new javax.swing.JPanel();
        txt_nombre = new javax.swing.JTextField();
        lbl_nombre = new javax.swing.JLabel();
        lbl_apellido = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        lbl_email = new javax.swing.JLabel();
        txt_apellido = new javax.swing.JTextField();
        lbl_numDeCliente = new javax.swing.JLabel();
        txt_edad = new javax.swing.JTextField();
        lbl_numDeCliente1 = new javax.swing.JLabel();
        lbl_telefono = new javax.swing.JLabel();
        txt_numDeCliente = new javax.swing.JTextField();
        txt_telefono = new javax.swing.JTextField();
        btn_guardar = new javax.swing.JButton();
        lbl_masculinoFemenino = new javax.swing.JLabel();
        radbtn_masculino = new javax.swing.JRadioButton();
        radbtn_femenino = new javax.swing.JRadioButton();
        lbl_ingresarCliente = new javax.swing.JLabel();
        pnl_mostrar = new javax.swing.JPanel();
        txt_datosCliente = new javax.swing.JTextArea();
        txt_ingresoNumDeCliente = new javax.swing.JTextField();
        btn_mostrarCliente = new javax.swing.JButton();
        btn_eliminarCliente = new javax.swing.JButton();
        lbl_fondo = new javax.swing.JLabel();
        pnl_actualizar = new javax.swing.JPanel();
        txt_nombreActualizar = new javax.swing.JTextField();
        lbl_nombreActualizar = new javax.swing.JLabel();
        lbl_apellidoActualizar = new javax.swing.JLabel();
        txt_emailActualizar = new javax.swing.JTextField();
        lbl_emailActualizar = new javax.swing.JLabel();
        txt_apellidoActualizar = new javax.swing.JTextField();
        txt_edadActualizar = new javax.swing.JTextField();
        lbl_edadActualizar = new javax.swing.JLabel();
        lbl_telefonoActualizar = new javax.swing.JLabel();
        txt_telefonoActualizar = new javax.swing.JTextField();
        lbl_actualizarCliente = new javax.swing.JLabel();
        pnl_fondoNegro = new javax.swing.JPanel();
        btn_actualizar = new javax.swing.JButton();
        txt_numClienteAActualizar = new javax.swing.JTextField();
        btn_buscarCliente = new javax.swing.JButton();
        img_lateral = new javax.swing.JLabel();
        pnl_tabla = new javax.swing.JPanel();
        txt_tablaCliente = new javax.swing.JTextField();
        btn_buscarCliente1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Cliente = new javax.swing.JTable();

        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        pnl_fondo.setBackground(new java.awt.Color(0, 0, 0));
        pnl_fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        img_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Logo.png"))); // NOI18N
        img_logo.setPreferredSize(new java.awt.Dimension(110, 100));
        pnl_fondo.add(img_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 6, 97, 109));

        btn_regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Return.png"))); // NOI18N
        btn_regresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_regresarMouseClicked(evt);
            }
        });
        pnl_fondo.add(btn_regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 6, -1, -1));

        lbl_titulo.setFont(new java.awt.Font("Georgia", 2, 36)); // NOI18N
        lbl_titulo.setForeground(new java.awt.Color(255, 255, 255));
        lbl_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_titulo.setText("Los Pollos Bélicos");
        pnl_fondo.add(lbl_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 14, 310, 40));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        pnl_fondo.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 60, 310, 10));

        pnl_cliente.setBackground(new java.awt.Color(0, 0, 0));
        pnl_cliente.setForeground(new java.awt.Color(255, 255, 255));
        pnl_cliente.setFocusable(false);
        pnl_cliente.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N

        pnl_ingresar.setBackground(new java.awt.Color(133, 5, 20));
        pnl_ingresar.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N

        txt_nombre.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N

        lbl_nombre.setFont(new java.awt.Font("Lucida Fax", 3, 14)); // NOI18N
        lbl_nombre.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nombre.setText("Nombre:");

        lbl_apellido.setFont(new java.awt.Font("Lucida Fax", 3, 14)); // NOI18N
        lbl_apellido.setForeground(new java.awt.Color(255, 255, 255));
        lbl_apellido.setText("Apellido:");

        txt_email.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N

        lbl_email.setFont(new java.awt.Font("Lucida Fax", 3, 14)); // NOI18N
        lbl_email.setForeground(new java.awt.Color(255, 255, 255));
        lbl_email.setText("Email:");

        txt_apellido.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N

        lbl_numDeCliente.setFont(new java.awt.Font("Lucida Fax", 3, 14)); // NOI18N
        lbl_numDeCliente.setForeground(new java.awt.Color(255, 255, 255));
        lbl_numDeCliente.setText("No. de Cliente:");

        txt_edad.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N

        lbl_numDeCliente1.setFont(new java.awt.Font("Lucida Fax", 3, 14)); // NOI18N
        lbl_numDeCliente1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_numDeCliente1.setText("Edad:");

        lbl_telefono.setFont(new java.awt.Font("Lucida Fax", 3, 14)); // NOI18N
        lbl_telefono.setForeground(new java.awt.Color(255, 255, 255));
        lbl_telefono.setText("Teléfono:");

        txt_numDeCliente.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N

        txt_telefono.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N

        btn_guardar.setBackground(new java.awt.Color(255, 185, 29));
        btn_guardar.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        btn_guardar.setText("Guardar");
        btn_guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_guardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_guardarMouseExited(evt);
            }
        });
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        lbl_masculinoFemenino.setFont(new java.awt.Font("Lucida Fax", 3, 14)); // NOI18N
        lbl_masculinoFemenino.setForeground(new java.awt.Color(255, 255, 255));
        lbl_masculinoFemenino.setText("Masculino/Femenino");

        radbtn_masculino.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        radbtn_masculino.setForeground(new java.awt.Color(255, 255, 255));
        radbtn_masculino.setText("Masculino");

        radbtn_femenino.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        radbtn_femenino.setForeground(new java.awt.Color(255, 255, 255));
        radbtn_femenino.setText("Femenino");

        lbl_ingresarCliente.setFont(new java.awt.Font("Lucida Fax", 3, 18)); // NOI18N
        lbl_ingresarCliente.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ingresarCliente.setText("Ingresar un nuevo Cliente");

        javax.swing.GroupLayout pnl_ingresarLayout = new javax.swing.GroupLayout(pnl_ingresar);
        pnl_ingresar.setLayout(pnl_ingresarLayout);
        pnl_ingresarLayout.setHorizontalGroup(
            pnl_ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_ingresarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_ingresarCliente)
                .addGap(146, 146, 146))
            .addGroup(pnl_ingresarLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(pnl_ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnl_ingresarLayout.createSequentialGroup()
                        .addComponent(lbl_telefono)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_ingresarLayout.createSequentialGroup()
                        .addGroup(pnl_ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_apellido)
                            .addComponent(lbl_nombre)
                            .addComponent(lbl_email)
                            .addComponent(lbl_numDeCliente1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnl_ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txt_apellido, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_email, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_edad, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnl_ingresarLayout.createSequentialGroup()
                        .addComponent(lbl_numDeCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_numDeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_ingresarLayout.createSequentialGroup()
                        .addComponent(lbl_masculinoFemenino)
                        .addGap(18, 18, 18)
                        .addComponent(radbtn_masculino)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(radbtn_femenino)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(btn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        pnl_ingresarLayout.setVerticalGroup(
            pnl_ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_ingresarLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lbl_ingresarCliente)
                .addGap(18, 18, 18)
                .addGroup(pnl_ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_nombre))
                .addGap(18, 18, 18)
                .addGroup(pnl_ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_apellido)
                    .addComponent(txt_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnl_ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_ingresarLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnl_ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_email)
                            .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnl_ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_numDeCliente1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_ingresarLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(btn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pnl_ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_ingresarLayout.createSequentialGroup()
                        .addComponent(txt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(pnl_ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_numDeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_numDeCliente)))
                    .addComponent(lbl_telefono))
                .addGap(33, 33, 33)
                .addGroup(pnl_ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_masculinoFemenino)
                    .addComponent(radbtn_masculino)
                    .addComponent(radbtn_femenino))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pnl_cliente.addTab("Ingresar", pnl_ingresar);

        pnl_mostrar.setBackground(new java.awt.Color(0, 0, 0));
        pnl_mostrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_datosCliente.setEditable(false);
        txt_datosCliente.setColumns(20);
        txt_datosCliente.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        txt_datosCliente.setForeground(new java.awt.Color(153, 153, 153));
        txt_datosCliente.setRows(5);
        txt_datosCliente.setText("Aquí aparecerán los datos de tu cliente...");
        pnl_mostrar.add(txt_datosCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 330, 220));

        txt_ingresoNumDeCliente.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        txt_ingresoNumDeCliente.setForeground(new java.awt.Color(153, 153, 153));
        txt_ingresoNumDeCliente.setText("Ingresa aquí el numero de cliente");
        txt_ingresoNumDeCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_ingresoNumDeClienteMouseClicked(evt);
            }
        });
        pnl_mostrar.add(txt_ingresoNumDeCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 330, 30));

        btn_mostrarCliente.setBackground(new java.awt.Color(255, 185, 29));
        btn_mostrarCliente.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        btn_mostrarCliente.setText("Mostrar Cliente");
        btn_mostrarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_mostrarClienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_mostrarClienteMouseExited(evt);
            }
        });
        btn_mostrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mostrarClienteActionPerformed(evt);
            }
        });
        pnl_mostrar.add(btn_mostrarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, -1, -1));

        btn_eliminarCliente.setBackground(new java.awt.Color(255, 51, 51));
        btn_eliminarCliente.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        btn_eliminarCliente.setText("Eliminar Cliente");
        btn_eliminarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_eliminarClienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_eliminarClienteMouseExited(evt);
            }
        });
        btn_eliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarClienteActionPerformed(evt);
            }
        });
        pnl_mostrar.add(btn_eliminarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, -1, -1));

        lbl_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/carbon.jpg"))); // NOI18N
        pnl_mostrar.add(lbl_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 380));

        pnl_cliente.addTab("Mostrar", pnl_mostrar);

        pnl_actualizar.setBackground(new java.awt.Color(133, 5, 20));
        pnl_actualizar.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        pnl_actualizar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_nombreActualizar.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        txt_nombreActualizar.setEnabled(false);
        pnl_actualizar.add(txt_nombreActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 59, 280, -1));

        lbl_nombreActualizar.setFont(new java.awt.Font("Lucida Fax", 3, 14)); // NOI18N
        lbl_nombreActualizar.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nombreActualizar.setText("Nombre:");
        pnl_actualizar.add(lbl_nombreActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 60, -1, -1));

        lbl_apellidoActualizar.setFont(new java.awt.Font("Lucida Fax", 3, 14)); // NOI18N
        lbl_apellidoActualizar.setForeground(new java.awt.Color(255, 255, 255));
        lbl_apellidoActualizar.setText("Apellido:");
        pnl_actualizar.add(lbl_apellidoActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 98, -1, -1));

        txt_emailActualizar.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        txt_emailActualizar.setEnabled(false);
        pnl_actualizar.add(txt_emailActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 135, 280, -1));

        lbl_emailActualizar.setFont(new java.awt.Font("Lucida Fax", 3, 14)); // NOI18N
        lbl_emailActualizar.setForeground(new java.awt.Color(255, 255, 255));
        lbl_emailActualizar.setText("Email:");
        pnl_actualizar.add(lbl_emailActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 136, -1, -1));

        txt_apellidoActualizar.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        txt_apellidoActualizar.setEnabled(false);
        pnl_actualizar.add(txt_apellidoActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 97, 280, -1));

        txt_edadActualizar.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        txt_edadActualizar.setEnabled(false);
        pnl_actualizar.add(txt_edadActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 173, 280, -1));

        lbl_edadActualizar.setFont(new java.awt.Font("Lucida Fax", 3, 14)); // NOI18N
        lbl_edadActualizar.setForeground(new java.awt.Color(255, 255, 255));
        lbl_edadActualizar.setText("Edad:");
        pnl_actualizar.add(lbl_edadActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 174, -1, -1));

        lbl_telefonoActualizar.setFont(new java.awt.Font("Lucida Fax", 3, 14)); // NOI18N
        lbl_telefonoActualizar.setForeground(new java.awt.Color(255, 255, 255));
        lbl_telefonoActualizar.setText("Teléfono:");
        pnl_actualizar.add(lbl_telefonoActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 215, -1, -1));

        txt_telefonoActualizar.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        txt_telefonoActualizar.setEnabled(false);
        pnl_actualizar.add(txt_telefonoActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 215, 280, -1));

        lbl_actualizarCliente.setFont(new java.awt.Font("Lucida Fax", 3, 18)); // NOI18N
        lbl_actualizarCliente.setForeground(new java.awt.Color(255, 255, 255));
        lbl_actualizarCliente.setText("Actualizar un Cliente");
        pnl_actualizar.add(lbl_actualizarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        pnl_fondoNegro.setBackground(new java.awt.Color(0, 0, 0));

        btn_actualizar.setBackground(new java.awt.Color(255, 185, 29));
        btn_actualizar.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        btn_actualizar.setText("Actualizar");
        btn_actualizar.setFocusable(false);
        btn_actualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_actualizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_actualizarMouseExited(evt);
            }
        });
        btn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarActionPerformed(evt);
            }
        });

        txt_numClienteAActualizar.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        txt_numClienteAActualizar.setForeground(new java.awt.Color(153, 153, 153));
        txt_numClienteAActualizar.setText("Ingresa aquí el numero de cliente");
        txt_numClienteAActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_numClienteAActualizarMouseClicked(evt);
            }
        });

        btn_buscarCliente.setBackground(new java.awt.Color(255, 185, 29));
        btn_buscarCliente.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        btn_buscarCliente.setText("Buscar Cliente");
        btn_buscarCliente.setFocusable(false);
        btn_buscarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_buscarClienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_buscarClienteMouseExited(evt);
            }
        });
        btn_buscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_fondoNegroLayout = new javax.swing.GroupLayout(pnl_fondoNegro);
        pnl_fondoNegro.setLayout(pnl_fondoNegroLayout);
        pnl_fondoNegroLayout.setHorizontalGroup(
            pnl_fondoNegroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_fondoNegroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_numClienteAActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(pnl_fondoNegroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_actualizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscarCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pnl_fondoNegroLayout.setVerticalGroup(
            pnl_fondoNegroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_fondoNegroLayout.createSequentialGroup()
                .addGroup(pnl_fondoNegroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_fondoNegroLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btn_actualizar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_buscarCliente))
                    .addGroup(pnl_fondoNegroLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(txt_numClienteAActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pnl_actualizar.add(pnl_fondoNegro, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 260, 400, 120));

        img_lateral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/GalloTenis.jpg"))); // NOI18N
        pnl_actualizar.add(img_lateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 0, 160, 380));

        pnl_cliente.addTab("Actualizar", pnl_actualizar);

        pnl_tabla.setBackground(new java.awt.Color(133, 5, 20));
        pnl_tabla.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N

        txt_tablaCliente.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        txt_tablaCliente.setForeground(new java.awt.Color(153, 153, 153));
        txt_tablaCliente.setText("Ingresa el numero de cliente");
        txt_tablaCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_tablaClienteMouseClicked(evt);
            }
        });

        btn_buscarCliente1.setBackground(new java.awt.Color(255, 185, 29));
        btn_buscarCliente1.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        btn_buscarCliente1.setText("Buscar Cliente");
        btn_buscarCliente1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_buscarCliente1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_buscarCliente1MouseExited(evt);
            }
        });
        btn_buscarCliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarCliente1ActionPerformed(evt);
            }
        });

        jScrollPane1.setBorder(null);

        tbl_Cliente.setBackground(new java.awt.Color(0, 0, 0));
        tbl_Cliente.setForeground(new java.awt.Color(255, 255, 255));
        tbl_Cliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_Cliente);

        javax.swing.GroupLayout pnl_tablaLayout = new javax.swing.GroupLayout(pnl_tabla);
        pnl_tabla.setLayout(pnl_tablaLayout);
        pnl_tablaLayout.setHorizontalGroup(
            pnl_tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_tablaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btn_buscarCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_tablaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
            .addGroup(pnl_tablaLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnl_tablaLayout.setVerticalGroup(
            pnl_tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_tablaLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(pnl_tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_buscarCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_tablaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pnl_cliente.addTab("Tabla Clientes", pnl_tabla);

        pnl_fondo.add(pnl_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 121, -1, 410));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_fondo, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_fondo, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_regresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_regresarMouseClicked
        objVtnPrincipal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_regresarMouseClicked

    private void btn_guardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_guardarMouseEntered
        btn_guardar.setBackground(new Color(0,0,0));
        btn_guardar.setForeground(Color.white);
    }//GEN-LAST:event_btn_guardarMouseEntered

    private void btn_guardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_guardarMouseExited
         btn_guardar.setBackground(new Color(255,185,29));
         btn_guardar.setForeground(Color.black);
    }//GEN-LAST:event_btn_guardarMouseExited

    private void btn_mostrarClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_mostrarClienteMouseEntered
        btn_mostrarCliente.setBackground(new Color(0,0,0));
        btn_mostrarCliente.setForeground(Color.white);
    }//GEN-LAST:event_btn_mostrarClienteMouseEntered

    private void btn_mostrarClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_mostrarClienteMouseExited
        btn_mostrarCliente.setBackground(new Color(255,185,29));
        btn_mostrarCliente.setForeground(Color.black);
    }//GEN-LAST:event_btn_mostrarClienteMouseExited

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        objVtnPrincipal.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        objCliente.setNombre(txt_nombre.getText());
        objCliente.setApellido(txt_apellido.getText());
        objCliente.setEmail(txt_email.getText());
        objCliente.setEdad(Integer.parseInt(txt_edad.getText()));
        objCliente.setNumDeTelefono(txt_telefono.getText());
        objCliente.setNumDeCliente(txt_numDeCliente.getText());
        if(radbtn_masculino.isSelected()){
            objCliente.setSexo("Masculino");
        }
        else{
            objCliente.setSexo("Femenino");
        }
        
        objBd.abrir_conexion();
        objBd.insertar_cliente(objCliente);
        objBd.cerrar_conexion();
        
        JOptionPane.showMessageDialog(this, "Datos almacenados");
        limpiar_cajas();
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void btn_mostrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mostrarClienteActionPerformed
        
        objBd.abrir_conexion();
        objCliente = objBd.consultar_cliente(txt_ingresoNumDeCliente.getText());
        objBd.cerrar_conexion();
        
        if(objCliente != null){
            txt_datosCliente.setForeground(Color.black);
            txt_datosCliente.setText(objCliente.mostrar_datos());
        }else{
            txt_ingresoNumDeCliente.setText("Ingresa aquí el numero de cliente");
            txt_ingresoNumDeCliente.setForeground(new Color(153,153,153));
            txt_datosCliente.setText("Aquí aparecerán los datos de tu cliente...");
            txt_datosCliente.setForeground(new Color(153,153,153));
            JOptionPane.showMessageDialog(this, "Cliente no fue encontrado en la base de datos")                                                                 ;
        }
        
        txt_datosCliente.setText(objCliente.mostrar_datos());
        
                                           
        
    }//GEN-LAST:event_btn_mostrarClienteActionPerformed

    private void btn_eliminarClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eliminarClienteMouseEntered
        btn_eliminarCliente.setBackground(new Color(133,4,19));
        btn_eliminarCliente.setForeground(Color.white);
    }//GEN-LAST:event_btn_eliminarClienteMouseEntered

    private void btn_eliminarClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eliminarClienteMouseExited
        btn_eliminarCliente.setBackground(new Color(255,51,51));
        btn_eliminarCliente.setForeground(Color.black);
    }//GEN-LAST:event_btn_eliminarClienteMouseExited

    private void btn_eliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarClienteActionPerformed
        objBd.abrir_conexion();
        objCliente = objBd.consultar_cliente(txt_ingresoNumDeCliente.getText());
        
        if(objCliente != null){
            objBd.eliminar_cliente(objCliente);
            JOptionPane.showMessageDialog(this,"Cliente eliminado de la base de datos");
         }else{
            JOptionPane.showMessageDialog(this,"Cliente no encontrado en la base de datos");         
        }
        limpiar_cajas();
        txt_ingresoNumDeCliente.setText("Ingresa aquí el numero de cliente");
        txt_ingresoNumDeCliente.setForeground(new Color(153,153,153));
        objBd.cerrar_conexion();    
                               
    }//GEN-LAST:event_btn_eliminarClienteActionPerformed

    private void btn_actualizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_actualizarMouseEntered
        btn_actualizar.setBackground(new Color(0,0,0));
        btn_actualizar.setForeground(Color.white);
    }//GEN-LAST:event_btn_actualizarMouseEntered

    private void btn_actualizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_actualizarMouseExited
        btn_actualizar.setBackground(new Color(255,185,29));
        btn_actualizar.setForeground(Color.black);
    }//GEN-LAST:event_btn_actualizarMouseExited

    private void btn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarActionPerformed
        
        objCliente.actualizar_cliente(objCliente,   
                              txt_nombreActualizar.getText(),
                              txt_apellidoActualizar.getText(),
                              txt_emailActualizar.getText(),
                              Integer.parseInt(txt_edadActualizar.getText()),
                              txt_telefonoActualizar.getText());
        objBd.abrir_conexion();
        objBd.actualizar_cliente(objCliente);
        objBd.cerrar_conexion();
        
        JOptionPane.showMessageDialog(this, "Cliente Actualizado");
        limpiar_cajas();
        deshabilitar_cajas();
                   
    }//GEN-LAST:event_btn_actualizarActionPerformed

    private void btn_buscarClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_buscarClienteMouseEntered
        btn_buscarCliente.setBackground(new Color(0,0,0));
        btn_buscarCliente.setForeground(Color.white);
    }//GEN-LAST:event_btn_buscarClienteMouseEntered

    private void btn_buscarClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_buscarClienteMouseExited
        btn_buscarCliente.setBackground(new Color(255,185,29));
        btn_buscarCliente.setForeground(Color.black);
    }//GEN-LAST:event_btn_buscarClienteMouseExited

    private void btn_buscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarClienteActionPerformed
        objBd.abrir_conexion();
        objCliente = objBd.consultar_cliente(txt_numClienteAActualizar.getText());
        objBd.cerrar_conexion();
        
        
        if(objCliente!=null) {
            JOptionPane.showMessageDialog(this, "Cliente encontrado, lo puedes actualizar");
            habilitar_cajas();
            txt_nombreActualizar.setText(objCliente.getNombre());
            txt_apellidoActualizar.setText(objCliente.getApellido());
            txt_emailActualizar.setText(objCliente.getEmail());
            txt_edadActualizar.setText(Integer.toString(objCliente.getEdad()));
            txt_telefonoActualizar.setText(objCliente.getNumDeTelefono());
            
            
        }else{
            JOptionPane.showMessageDialog(this, "Cliente no encontrado");
            deshabilitar_cajas();
            txt_numClienteAActualizar.setText("Ingresa aquí el numero de cliente");
            txt_numClienteAActualizar.setForeground(new Color(153,153,153));
        }  
    }//GEN-LAST:event_btn_buscarClienteActionPerformed

    private void btn_buscarCliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarCliente1ActionPerformed
        objBd.abrir_conexion();
        if(txt_tablaCliente.getText().isBlank() || "Ingresa el numero de cliente".equals(txt_tablaCliente.getText()))
            modeloCliente = objBd.consultar_cliente(modeloCliente);
        else
            modeloCliente = objBd.consultar_cliente(txt_tablaCliente.getText(), modeloCliente);
        
        if(modeloCliente.getRowCount()!= 0)
            tbl_Cliente.setModel(modeloCliente);
        else
            JOptionPane.showMessageDialog(this, "Cliente no se encuentra en la base de datos");
        
        objBd.cerrar_conexion();
        limpiar_cajas();
    }//GEN-LAST:event_btn_buscarCliente1ActionPerformed

    private void btn_buscarCliente1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_buscarCliente1MouseExited
        btn_buscarCliente1.setBackground(new Color(255,185,29));
        btn_buscarCliente1.setForeground(Color.black);
    }//GEN-LAST:event_btn_buscarCliente1MouseExited

    private void btn_buscarCliente1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_buscarCliente1MouseEntered
        btn_buscarCliente1.setBackground(new Color(0,0,0));
        btn_buscarCliente1.setForeground(Color.white);
    }//GEN-LAST:event_btn_buscarCliente1MouseEntered

    private void txt_ingresoNumDeClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_ingresoNumDeClienteMouseClicked
        txt_ingresoNumDeCliente.setText("");
        txt_ingresoNumDeCliente.setForeground(Color.black);
    }//GEN-LAST:event_txt_ingresoNumDeClienteMouseClicked

    private void txt_numClienteAActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_numClienteAActualizarMouseClicked
        txt_numClienteAActualizar.setText("");
        txt_numClienteAActualizar.setForeground(Color.black);
    }//GEN-LAST:event_txt_numClienteAActualizarMouseClicked

    private void txt_tablaClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_tablaClienteMouseClicked
        txt_tablaCliente.setText("");
        txt_tablaCliente.setForeground(Color.black);
    }//GEN-LAST:event_txt_tablaClienteMouseClicked
    public void limpiar_cajas(){
        txt_nombre.setText("");
        txt_apellido.setText("");
        txt_email.setText("");
        txt_edad.setText("");
        txt_telefono.setText("");
        txt_numDeCliente.setText("");
        txt_datosCliente.setText("");
        
        txt_nombreActualizar.setText("");
        txt_apellidoActualizar.setText("");
        txt_emailActualizar.setText("");
        txt_edadActualizar.setText("");
        txt_telefonoActualizar.setText("");
        txt_numClienteAActualizar.setText("");
    }
    
    public void habilitar_cajas(){
        txt_nombreActualizar.setEnabled(true);
        txt_apellidoActualizar.setEnabled(true);
        txt_emailActualizar.setEnabled(true);
        txt_edadActualizar.setEnabled(true);
        txt_telefonoActualizar.setEnabled(true);
    }
    public void deshabilitar_cajas(){
        txt_nombreActualizar.setEnabled(false);
        txt_apellidoActualizar.setEnabled(false);
        txt_emailActualizar.setEnabled(false);
        txt_edadActualizar.setEnabled(false);
        txt_telefonoActualizar.setEnabled(false);
    }
            
            
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VtnCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VtnCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VtnCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VtnCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VtnCliente().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_actualizar;
    private javax.swing.JButton btn_buscarCliente;
    private javax.swing.JButton btn_buscarCliente1;
    private javax.swing.JButton btn_eliminarCliente;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_mostrarCliente;
    private javax.swing.JLabel btn_regresar;
    private javax.swing.ButtonGroup btngroup_masculinoFemenino;
    private javax.swing.JLabel img_lateral;
    private javax.swing.JLabel img_logo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_actualizarCliente;
    private javax.swing.JLabel lbl_apellido;
    private javax.swing.JLabel lbl_apellidoActualizar;
    private javax.swing.JLabel lbl_edadActualizar;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_emailActualizar;
    private javax.swing.JLabel lbl_fondo;
    private javax.swing.JLabel lbl_ingresarCliente;
    private javax.swing.JLabel lbl_masculinoFemenino;
    private javax.swing.JLabel lbl_nombre;
    private javax.swing.JLabel lbl_nombreActualizar;
    private javax.swing.JLabel lbl_numDeCliente;
    private javax.swing.JLabel lbl_numDeCliente1;
    private javax.swing.JLabel lbl_telefono;
    private javax.swing.JLabel lbl_telefonoActualizar;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JPanel pnl_actualizar;
    private javax.swing.JTabbedPane pnl_cliente;
    private javax.swing.JPanel pnl_fondo;
    private javax.swing.JPanel pnl_fondoNegro;
    private javax.swing.JPanel pnl_ingresar;
    private javax.swing.JPanel pnl_mostrar;
    private javax.swing.JPanel pnl_tabla;
    private javax.swing.JRadioButton radbtn_femenino;
    private javax.swing.JRadioButton radbtn_masculino;
    private javax.swing.JTable tbl_Cliente;
    private javax.swing.JTextField txt_apellido;
    private javax.swing.JTextField txt_apellidoActualizar;
    private javax.swing.JTextArea txt_datosCliente;
    private javax.swing.JTextField txt_edad;
    private javax.swing.JTextField txt_edadActualizar;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_emailActualizar;
    private javax.swing.JTextField txt_ingresoNumDeCliente;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_nombreActualizar;
    private javax.swing.JTextField txt_numClienteAActualizar;
    private javax.swing.JTextField txt_numDeCliente;
    private javax.swing.JTextField txt_tablaCliente;
    private javax.swing.JTextField txt_telefono;
    private javax.swing.JTextField txt_telefonoActualizar;
    // End of variables declaration//GEN-END:variables
}
